default:
  deps: [test]

update-deps:
  desc: Updates dependencies
  cmds:
  - glide install --strip-vendor
  # - dep ensure
  # - dep ensure -update

lint:
  desc: Checks code style
  cmds:
    - gofmt -d -s ./pkg/*.go
    - go vet ./pkg/...
  silent: true

lint-fix:
  desc: Fixes code style
  cmds:
    - gofmt -w -s ./pkg/*.go

test:
  desc: Runs go tests
  cmds:
    - go test -race  ./pkg/...

test-coverage:
  desc: Runs go tests and calucates test coverage
  cmds:
    - go test -coverprofile=c.out ./pkg/...
